version: "3.8"
name: "databases-fullstack"
services:
  db:
    image: "mysql:8.3.0"
    restart: unless-stopped
    ports:
      - "6000:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  backend:
    build: "backend"
    restart: unless-stopped
    ports:
      - "6001:6001"
    volumes:
      - "./backend:/app"
  frontend:
    build: "frontend"
    restart: unless-stopped
    ports:
      - "6002:6002"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
